services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server-2022
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Admin1234
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
      - ./Crea_BD.sql:/docker-entrypoint-initdb.d/01-Crea_BD.sql
      - ./Carga_Datos.sql:/docker-entrypoint-initdb.d/02-Carga_Datos.sql
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Admin1234 -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

volumes:
  sqlvolume:
